[package]
name = 'webcam-proxy'
version = '0.1.0'
authors = ['Sami Salonen']
edition = '2018'

[dependencies]
image = '0.23.8'
imageproc = '0.21.0'
hyper = '0.13.7'
bytes = '0.5.6'
lazy_static = '1.4.0'
hyper-tls = '0.4.3'
toml = '0.5.6'
url = '2.1.1'
rusttype = '0.9.2'
rand = '0.7.3'
thiserror = '1.0.20'
futures = '0.3.5'
tracing = '0.1.19'
tracing-futures = '0.2.4'
humantime = '2.0.1'
chrono = '0.4.15'
time = '0.1'
lab = '0.8.1'
img_hash = '3.1.0'

[dependencies.tracing-subscriber]
version = '0.2.11'
features = ['env-filter']

[dependencies.tokio]
version = '0.2.21'
features = [
    'time',
    'stream',
    'fs',
    'sync',
]

[dependencies.serde]
version = '1.0.114'
features = ['derive']
