[package]
name = 'webcam-proxy'
version = '0.1.0'
authors = ['Sami Salonen']
edition = '2018'

[dependencies]
image = '0.23.0'
imageproc = '0.20.0'
hyper = '0.13.5'
bytes = '0.5.4'
lazy_static = '1.4.0'
hyper-tls = '0.4.1'
toml = '0.5.6'
url = '2.1.1'
rusttype = '0.8.2'
futures-locks-pre = '0.5.1-pre'
rand = '0.7.3'
failure = '0.1.7'
futures = '0.3.4'
tracing = '0.1.13'
tracing-futures = '0.2.4'
tracing-subscriber = '0.2.5'
humantime = '2.0.0'
chrono = '0.4.11'
time = '0.1'

[dependencies.tokio]
version = '0.2.19'
features = [
    'time',
    'stream',
]

[dependencies.serde]
version = '1.0.105'
features = ['derive']
